spring:
  application:
    name: home-temperature
  redis:
    host: default-redis-ro.kn9v0u.ng.0001.use1.cache.amazonaws.com
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: -1
        min-idle: 1    

server:
  port: 9052

messages:
  basename: messages
  default:
    country: BR
    language: PT
    encoding: UTF-8
